### ISSUE TITLE
Uploading my own network

### ISSUE THREAD

**Issue by kirkegross** [JCBrouwer/maua-stylegan2#11]
Hi!

Thanks for this code.
If I want to upload my own model can it be and .h5 file?
And how exactly should I upload it?
<img width="837" alt="Screenshot 2021-02-03 at 13 58 08" src="https://user-images.githubusercontent.com/23554239/106757212-fed40e80-6627-11eb-8121-4d9a823155d1.png">

Best,
Kirke

**Comment by JCBrouwer** [comment]
Hello,

You can upload your model in a couple different ways. Probably the easiest/fastest is to upload it to your own google drive and then put the link to it in `!gdown ...` . Alternatively you can mount your drive to the colab and access it from there.

You can also just drag and drop it into the file browser on the left of colab, although in my experience the upload and download speed directly to colab is suuuper slow.

.h5 won't work right away, the convert_weight.py script expects a .pkl. What repository did you use to train the .h5 model? Maybe there's also something to convert to .pkl or .pt from there? Otherwise you'll need to write the conversion yourself or find someone else that's done it online.

**Comment by kirkegross** [comment]
Thank you!
