### ISSUE TITLE
How to achieve 1920x1080 resolution in interpolation videos?

### ISSUE THREAD

**Issue by aertist** [JCBrouwer/maua-stylegan2#14]
Hey! Can you explain how you achieved that resolution in [this](https://youtu.be/2LxHRGppdpA) YT video of yours. (I'm a newbie)

Also can tell more about what was the dataset you used to train this model? And can you share the dataset or model if its okay with you? 😅

**Comment by JCBrouwer** [comment]
You can find some examples that generate at 1920x1080 resolution in `audioreactive/examples`, but here's a bit of an explanation:

The crucial point for the 1920x1080 resolution is that the generator is almost completely convolutional. By default, only the learned constant layer has a fixed size (even this can be made convolutional, e.g. by using the train.py in my repo with --noconst). The rest of the layers can accept any input size and either double the spatial size (upsampling layers) or increase the number of filters (conv layers).

The trick is then: if you reshape the input to one of the layers to be twice as wide, the final output will be twice as wide as well. One good way to make your input wider is to put two copies next to each other (that way you know that the input makes sense, setting some constant or using random noise to fill out the width doesn't always look as good). What I've found works nice for abstract/textural networks, is rather than put two copies next to eachother is to pad both sides with a mirrored version of that half. That way the main focus of the image is centered. Also, adding some noise to the wider version can help to disguise the fact that the sides are a copy of the center part. This is exactly what the code in the examples does:
```
def get_bends(args):
    transform = th.nn.Sequential(
        th.nn.ReplicationPad2d((2, 2, 0, 0)),
        ar.AddNoise((0.025 * th.randn(size=(1, 1, 4, 8))),
    )
    return [{"layer": 0}, "transform": transform]
```
First pad the 4x4 constant layer out 2 pixels left and right, then add some weak noise of size 4x8.

I'm cheating a tiny bit at the end, because the output is really 2048x1024. I crop this down to 1824x1024  (16:9 resolution) and then just scale it up to 1920x1080 with bilinear interpolation. If you wanted to, you could perform the transformation on the layer where the intermediate features are 8x8 though, and expand to exactly a 16x9 resolution (e.g. double width and add one extra row). Something like this:
```
def get_bends(args):
    transform = th.nn.Sequential(
        th.nn.ReplicationPad2d((4, 4, 1, 0)),
        ar.AddNoise((0.025 * th.randn(size=(1, 1, 9, 16))),
    )
    return [{"layer": 4}, "transform": transform]
```
Although, you'd need to adjust you get_noise() function to return the right shapes for the different layers.

Hopes this helps make it a bit more clear.

RE: my dataset and model. I won't be sharing these as I don't have the permission/copyright to share the data and the model is really the only 'secret sauce' I have left after publishing this repository. If you'd like to recreate something similar: the model was trained on sci-fi and concept art I scraped from the internet. I upscaled the original images (~1500 if I remember correctly), cropped out multiple squares from all over the image at different zoom levels, then applied rotations randomly. In the end the training set was ~30k images.

**Comment by aertist** [comment]
It's aight. so you trained it using stylegan2 or stylegan2-ada ? 30k is a super big dataset for the stylegan2-ada version 😳

**Comment by JCBrouwer** [comment]
Either one works, I've trained on this dataset with both versions
